a200_0000:
  controller_manager:
    ros__parameters:
      update_rate: 50
      use_sim_time: True
      joint_state_broadcaster.type: 'joint_state_broadcaster/JointStateBroadcaster'
      platform_velocity_controller.type: 'diff_drive_controller/DiffDriveController'
      arm_0_joint_trajectory_controller.type: 'joint_trajectory_controller/JointTrajectoryController'
      arm_0_gripper_controller.type: 'position_controllers/GripperActionController'
  platform_velocity_controller:
    ros__parameters:
      use_sim_time: True
      left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
      right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
      wheel_separation: 0.555
      wheels_per_side: 1
      wheel_radius: 0.1651
      wheel_separation_multiplier: 1.875
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0
      publish_rate: 50.0
      odom_frame_id: 'odom'
      base_frame_id: 'base_link'
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      open_loop: False
      enable_odom_tf: False
      tf_frame_prefix_enable: False
      cmd_vel_timeout: 0.5
      use_stamped_vel: False
      preserve_turning_radius: True
      publish_cmd: True
      publish_wheel_data: True
      linear.x.has_velocity_limits: True
      linear.x.has_acceleration_limits: True
      linear.x.has_jerk_limits: False
      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      linear.x.max_acceleration: 1.0
      linear.x.max_jerk: 0.0
      linear.x.min_jerk: 0.0
      angular.z.has_velocity_limits: True
      angular.z.has_acceleration_limits: True
      angular.z.has_jerk_limits: False
      angular.z.max_velocity: 1.0
      angular.z.min_velocity: -1.0
      angular.z.max_acceleration: 1.0
      angular.z.min_acceleration: -1.0
      angular.z.max_jerk: 0.0
      angular.z.min_jerk: 0.0
  arm_0_joint_trajectory_controller:
    ros__parameters:
      joints: ['arm_0_joint_1', 'arm_0_joint_2', 'arm_0_joint_3', 'arm_0_joint_4', 'arm_0_joint_5', 'arm_0_joint_6']
      command_interfaces: ['position']
      state_interfaces: ['position', 'velocity']
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: False
      constraints.stopped_velocity_tolerance: 0.0
      constraints.goal_time: 0.0
      use_sim_time: True
  arm_0_gripper_controller:
    ros__parameters:
      default: True
      joint: 'arm_0_gripper_right_finger_bottom_joint'
      allow_stalling: True
      use_sim_time: True
